import Header from './components/Header'
import './globals.css'
import { Mulish, Roboto } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const mulish = Mulish({
  weight: ['400','500','700','900'],// WE CAN USE AARRY TO SET DIFFERENT WEIGHT 
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={mulish.className}>
      <Header/>
        {children}
        
        </body>
    </html>
  )
}
