'use client'
import { Suspense } from 'react'
import Header from './components/Header'
import './globals.css'
import { Mulish, Roboto } from 'next/font/google'
import Loading from './loading'
import { Provider } from 'react-redux'
import { store } from '@/Redux/Store'

// const inter = Inter({ subsets: ['latin'] })
const mulish = Mulish({
  weight: ['400','500','700','900'],// WE CAN USE AARRY TO SET DIFFERENT WEIGHT 
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={mulish.className}>
      
      <Header/>
      <Suspense fallback={<Loading/>}/>
      <Provider store={store}>
        {children}
        </Provider>
        </body>
    </html>
  )
}
